name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
jobs:
  build1:
    runs-on: ubuntu-latest
    env:
      SUPER_SECRET: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          rm -rf random.txt
          echo $(date "+%Y%m%d%H%M%S") >> random.txt
          git config --global user.email "535128725@qq.com"
          git config --global user.name "niniubiwoc"
          git add .
          git commit -m $(date "+%Y%m%d%H%M%S")
          git push https://$TOKEN@github.com/niniula/test.git
